### ISSUE TITLE
Scrolling of elements in Chromium based browsers duplicates the top entry

### ISSUE THREAD

**Issue by ThomBreugelmans** [WISVCH/AoCH#4]
As the title implies on Chromium based browsers the top element gets duplicated. Likely something to do with the order in which the `transitionend` listeners are called, but needs further triage.
To note: on firefox it works alright, no issues there (yay browsers).

**example**:
![image](https://github.com/user-attachments/assets/23e778f0-0414-4e15-a76a-70fc130f5cfe)

**suggestion**:
make not the single list elements move, but the whole container + some extra and when it has "looped" reset the position. This solution should also make use of clipping so that elements outside the boundary of the parent aren't shown (looks nicer that way).

**Comment by KasperVaessen** [comment]
not relevant anymore :)

**Comment by ThomBreugelmans** [comment]
Hell of a way to resolve this big/issue, some 1300+ lines hahaha

resolved in f740f3d
