### ISSUE TITLE
`/:year/day/:day/leaderboard/today` endpoint showing `/leaderboard/today`

### ISSUE THREAD

**Issue by ThomBreugelmans** [WISVCH/AoCH#6]
I believe this endpoint should be used to show the leaderboard of a specific date, however this only shows the leaderboard of the current day, not the given day.

Not sure if the other endpoints with similar functionality do work, but that is something that should perhaps be looked at.

**Comment by KasperVaessen** [comment]
Solved :)

**Comment by ThomBreugelmans** [comment]
Cool beans, works like a charm!
